In [2]:
import numpy as np
np.arange?

Docstring:
arange([start,] stop[, step,], dtype=None, *, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.  The interva

In [3]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
X = np.arange(15).reshape(3,5)

In [5]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

基本属性

In [6]:
x.ndim

1

In [7]:
X.ndim

2

In [8]:
x.shape

(10,)

In [9]:
X.shape

(3, 5)

In [10]:
x.size

10

In [11]:
X.size

15

### numpy.array的数据访问

In [12]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
x[0]

0

In [14]:
x[-1]

9

In [15]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [17]:
X[0][2]

2

In [18]:
X[(0,1)]

1

In [19]:
X[2,2]

12

In [20]:
x[0:5]

array([0, 1, 2, 3, 4])

In [21]:
x[5:]

array([5, 6, 7, 8, 9])

In [22]:
x[::2]

array([0, 2, 4, 6, 8])

In [23]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [24]:
X[:2,:3]

array([[0, 1, 2],
       [5, 6, 7]])

In [25]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [26]:
X[:2]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [27]:
X[:2, ::2]

array([[0, 2, 4],
       [5, 7, 9]])

In [28]:
X[::-1, ::-1]

array([[14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [29]:
X[0]

array([0, 1, 2, 3, 4])

In [31]:
X[0,:].ndim

1

In [32]:
X[:0]

array([], shape=(0, 5), dtype=int32)

In [34]:
X[:,0]

array([ 0,  5, 10])

In [35]:
subX = X[:2,:3].copy()

### Reshape

In [36]:
x.shape

(10,)

In [37]:
x.ndim

1

In [38]:
x.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [39]:
A = x.reshape(1, 10)

In [40]:
A

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [41]:
A.ndim

2

In [43]:
x.reshape(2, -1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### 合并操作

In [45]:
x = np.array([1,2,3])
y = np.array([1,2,3])

In [46]:
np.concatenate([x,y])

array([1, 2, 3, 1, 2, 3])

In [47]:
z = np.array([66,666,6666])

In [48]:
np.concatenate([x,y,z])

array([   1,    2,    3,    1,    2,    3,   66,  666, 6666])

In [57]:
A = np.array([[1,2,3], [4,5,6]])

In [58]:
np.concatenate([A, A])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [59]:
np.concatenate([A,A], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [60]:
B = np.full((2,2), 100)

In [61]:
B

array([[100, 100],
       [100, 100]])

In [62]:
np.hstack([A,B])

array([[  1,   2,   3, 100, 100],
       [  4,   5,   6, 100, 100]])

### 分割操作

In [63]:
x= np.arange(10)

In [64]:
np.split(x, 2)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [65]:
np.split(x, [3,7])

[array([0, 1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])]

In [66]:
A = np.arange(16).reshape((4, -1))

In [67]:
A


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [68]:
np.split(A, [2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [69]:
np.split(A, [2], axis=1)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [71]:
data = np.arange(16).reshape((4,-1))
X, y = np.hsplit(data, [-1])

In [72]:
X

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [73]:
y

array([[ 3],
       [ 7],
       [11],
       [15]])

In [74]:
y[:,0]

array([ 3,  7, 11, 15])

### 矩阵运算

In [79]:
A = np.arange(4).reshape(2, -1)
A

array([[0, 1],
       [2, 3]])

In [81]:
B = np.full( (2,2), 10)
B

array([[10, 10],
       [10, 10]])

In [82]:
A+B

array([[10, 11],
       [12, 13]])

In [83]:
A-B

array([[-10,  -9],
       [ -8,  -7]])

In [84]:
A*B

array([[ 0, 10],
       [20, 30]])

In [85]:
A/B

array([[0. , 0.1],
       [0.2, 0.3]])

In [86]:
A.dot(B)

array([[10, 10],
       [50, 50]])

In [87]:
A.T

array([[0, 2],
       [1, 3]])

## 向量和矩阵运算

In [88]:
v=np.array([1,2])

In [89]:
A

array([[0, 1],
       [2, 3]])

In [90]:
v+A

array([[1, 3],
       [3, 5]])

In [91]:
np.vstack([v] * A.shape[0])

array([[1, 2],
       [1, 2]])

In [92]:
np.tile(v, (2,2))

array([[1, 2, 1, 2],
       [1, 2, 1, 2]])

In [93]:
v*A

array([[0, 2],
       [2, 6]])

In [94]:
v.dot(A)

array([4, 7])

In [95]:
A.dot(v)

array([2, 8])

In [96]:
A.dot(v.T)

array([2, 8])

### 矩阵的逆运算

In [97]:
np.linalg.inv(A)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [98]:
invA = np.linalg.inv(A)

In [99]:
A.dot(invA)

array([[1., 0.],
       [0., 1.]])

In [100]:
X = np.arange(16).reshape(2, -1)

In [101]:
X


array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [102]:
pingvX = np.linalg.pinv(X)

In [103]:
pingvX.shape

(8, 2)

In [104]:
pingvX.dot(X)

array([[ 4.16666667e-01,  3.33333333e-01,  2.50000000e-01,
         1.66666667e-01,  8.33333333e-02, -1.66533454e-16,
        -8.33333333e-02, -1.66666667e-01],
       [ 3.33333333e-01,  2.73809524e-01,  2.14285714e-01,
         1.54761905e-01,  9.52380952e-02,  3.57142857e-02,
        -2.38095238e-02, -8.33333333e-02],
       [ 2.50000000e-01,  2.14285714e-01,  1.78571429e-01,
         1.42857143e-01,  1.07142857e-01,  7.14285714e-02,
         3.57142857e-02, -1.56125113e-16],
       [ 1.66666667e-01,  1.54761905e-01,  1.42857143e-01,
         1.30952381e-01,  1.19047619e-01,  1.07142857e-01,
         9.52380952e-02,  8.33333333e-02],
       [ 8.33333333e-02,  9.52380952e-02,  1.07142857e-01,
         1.19047619e-01,  1.30952381e-01,  1.42857143e-01,
         1.54761905e-01,  1.66666667e-01],
       [-3.96868870e-17,  3.57142857e-02,  7.14285714e-02,
         1.07142857e-01,  1.42857143e-01,  1.78571429e-01,
         2.14285714e-01,  2.50000000e-01],
       [-8.33333333e-02, -2.380952

In [105]:
X.dot(pingvX)

array([[ 1.00000000e+00, -2.60208521e-16],
       [ 9.71445147e-17,  1.00000000e+00]])

### 聚合操作

In [106]:
import numpy as np
L = np.random.random(100)

In [107]:
L

array([0.74995278, 0.54928839, 0.45607469, 0.95190301, 0.59686277,
       0.58486622, 0.37322086, 0.93327026, 0.50986146, 0.01737411,
       0.13006016, 0.54162339, 0.16216215, 0.89685713, 0.73071729,
       0.20087925, 0.6569393 , 0.75993246, 0.39877191, 0.17514732,
       0.51937968, 0.39482907, 0.98150037, 0.84445843, 0.5890842 ,
       0.32080304, 0.02627789, 0.53371486, 0.21835252, 0.63255387,
       0.06149508, 0.0455255 , 0.45073798, 0.45369854, 0.58904811,
       0.89128931, 0.67521981, 0.53761497, 0.30008279, 0.79755747,
       0.89281543, 0.46323684, 0.81100364, 0.12416339, 0.12238993,
       0.16924366, 0.66439097, 0.47740858, 0.64016325, 0.38566888,
       0.68723486, 0.59862254, 0.61210441, 0.54680663, 0.96686041,
       0.33376119, 0.66419192, 0.80223886, 0.75869725, 0.78019288,
       0.90871868, 0.85704007, 0.45441272, 0.00111543, 0.37490468,
       0.03801853, 0.65049184, 0.44231019, 0.84762171, 0.76822166,
       0.83577184, 0.75005591, 0.03364123, 0.94156846, 0.54150

In [108]:
sum(L)

50.9397061179288

In [109]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

51.1 ms ± 478 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
361 µs ± 6.97 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [110]:
np.min(big_array)

1.3669565035456799e-06

In [111]:
big_array.max()

0.9999989989192846

In [115]:
X = np.arange(16).reshape(4, -1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [113]:
np.sum(X)

120

In [114]:
np.sum(X, axis=0)

array([24, 28, 32, 36])

In [116]:
np.sum(X , axis=1)

array([ 6, 22, 38, 54])

In [117]:
np.prod(X)

0

In [118]:
np.prod(X+1)

2004189184

In [119]:
np.mean(X)

7.5

In [120]:
np.median(X)

7.5

In [121]:
for percent in [0, 25, 50, 75, 100]:
  print(np.percentile(big_array, percent))

1.3669565035456799e-06
0.24985299488133034
0.5002512097654559
0.7502540645478051
0.9999989989192846


In [122]:
np.var(big_array)

0.0833989436327425

In [123]:
np.std(big_array)

0.28878875260775394

In [124]:
x = np.random.normal(0, 1, size =100000)

In [125]:
np.mean(x)

-0.0018344303313150153

In [126]:
np.std(x)

0.9995746383751121

## 索引

In [127]:
np.min(x)

-4.070454890239008

In [128]:
np.argmin(x)

56953

In [129]:
x[np.argmin(x)]

-4.070454890239008

### 排序和使用索引

In [130]:
x = np.arange(16)

In [131]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [132]:
np.random.shuffle(x)

In [133]:
x

array([11, 14,  5,  7,  6, 13, 15,  1,  0,  4,  8,  2, 10, 12,  3,  9])

In [134]:
np.sort(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [135]:
x.sort()

In [136]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [137]:
X = np.random.randint(10, size=(4,4))
X

array([[6, 4, 5, 3],
       [2, 5, 3, 3],
       [1, 3, 0, 9],
       [2, 1, 3, 3]])

In [138]:
np.sort(X)

array([[3, 4, 5, 6],
       [2, 3, 3, 5],
       [0, 1, 3, 9],
       [1, 2, 3, 3]])

In [140]:
np.sort(X , axis=0)

array([[1, 1, 0, 3],
       [2, 3, 3, 3],
       [2, 4, 3, 3],
       [6, 5, 5, 9]])

In [141]:
np.random.shuffle(x)

In [142]:
x

array([ 8, 13,  4,  9,  0,  5, 11, 12,  3,  7,  6, 14, 15, 10,  2,  1])

In [143]:
np.argsort(x)

array([ 4, 15, 14,  8,  2,  5, 10,  9,  0,  3, 13,  6,  7,  1, 11, 12],
      dtype=int64)

In [144]:
np.partition(x, 3)

array([ 1,  2,  0,  3,  4,  5,  6,  7,  8, 13, 11, 14, 15, 10,  9, 12])