In [21]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

In [22]:
iris = datasets.load_iris()

In [23]:
X=iris.data

In [24]:
y=iris.target

In [25]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [26]:
X.shape

(150, 4)

In [27]:
y.shape

(150,)

# train_test_split

In [28]:
shuffle_indexs = np.random.permutation(len(X))

In [29]:
shuffle_indexs

array([ 38, 117, 127, 121,  56,  15,  67,  89,  65,  76,  27,  57,  16,
        62,  72,  53,  25, 108, 120,  46, 103,  20,  23,  39, 128,  75,
       118,  99,  11,  58, 130, 134,  33, 101,  93,  44,  48,  52,  35,
       133,  41, 102, 100,  73, 131, 124,   7,   5, 147, 126,  19, 115,
        10, 137,  90, 142,  47, 125,  55,  74,  24,   0,   6,  66,  21,
       107,   2,   8,  26,  79,  28, 138, 143,  14, 132, 145,  49,  60,
        81, 106,  37,  32,  40, 109,  78,  12,  91,  82,  36,  64,  45,
       140,  88,  97,   9,  92, 139, 129,  71, 110, 113, 149,   4,  17,
       136,  96,  59,   3,  80,  77,  43,  86, 119,  54,  70,   1, 111,
       135,  94,  22, 114, 122,  31,  98,  68, 144, 146, 116,  29,  30,
        61,  95, 105,  51,  87,  85,  50,  63,  84, 123,  42, 148,  69,
        83,  13, 112,  18,  34, 141, 104])

In [30]:
from playML.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [31]:
from playML.knn import KNNClassifier
my_knn_clf = KNNClassifier(k=3)

In [32]:
my_knn_clf.fit(X_train, y_train)

KNN(k=3)

In [33]:
y_predict = my_knn_clf.predict(X_test)

In [34]:
y_test

array([1, 0, 2, 0, 2, 0, 0, 0, 1, 2, 2, 0, 1, 1, 2, 1, 0, 1, 0, 2, 0, 1,
       2, 2, 1, 0, 0, 1, 2, 0])

In [35]:
sum(y_predict == y_test)

30