# 梯度下降法的向量化

In [1]:
import numpy as np
from sklearn.datasets import fetch_openml

boston = fetch_openml(name='boston',version="1", as_frame=False)

c:\Users\ACER\.conda\envs\ml\Lib\site-packages\sklearn\datasets\_openml.py:968: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


In [2]:
X = boston.data
y = boston.target

In [3]:
import matplotlib.pyplot as plt

In [4]:
X = X[y < 50.0]
y = y[y < 50.0]

In [5]:
X

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [6]:
from playML.model_selection import train_test_split
X_train, X_test,y_train,  y_test = train_test_split(X, y, seed=666)

In [7]:
from playML.LinearRegression import LinearRegression
lin_reg1 = LinearRegression()
%time lin_reg1.fit_normal(X_train, y_train)

CPU times: total: 125 ms
Wall time: 6 ms


LinearRegression()

In [8]:
lin_reg1.score(X_test, y_test)

0.7993270271395859

In [9]:
lin_reg2 = LinearRegression()

In [10]:
lin_reg2.fit_gd(X_train, y_train)

c:\Users\ACER\.conda\envs\ml\Lib\site-packages\numpy\core\fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
e:\projects\ml\playML\LinearRegression.py:30: RuntimeWarning: overflow encountered in square
  return np.sum((y - X_b.dot(theta)) ** 2) / len(X_b)
e:\projects\ml\playML\LinearRegression.py:51: RuntimeWarning: invalid value encountered in double_scalars
  if(abs(J(theta , X_b, y) - J(last_theta, X_b, y)) < epsilon ):


LinearRegression()

In [11]:
lin_reg2.coef_

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

In [13]:
X_train[:10,:]

array([[1.42362e+01, 0.00000e+00, 1.81000e+01, 0.00000e+00, 6.93000e-01,
        6.34300e+00, 1.00000e+02, 1.57410e+00, 8.00000e+00, 6.66000e+02,
        2.02000e+01, 3.96900e+02, 2.03200e+01],
       [3.67822e+00, 0.00000e+00, 1.81000e+01, 0.00000e+00, 7.70000e-01,
        5.36200e+00, 9.62000e+01, 2.10360e+00, 8.00000e+00, 6.66000e+02,
        2.02000e+01, 3.80790e+02, 1.01900e+01],
       [1.04690e-01, 4.00000e+01, 6.41000e+00, 1.00000e+00, 4.47000e-01,
        7.26700e+00, 4.90000e+01, 4.78720e+00, 3.00000e+00, 2.54000e+02,
        1.76000e+01, 3.89250e+02, 6.05000e+00],
       [1.15172e+00, 0.00000e+00, 8.14000e+00, 0.00000e+00, 5.38000e-01,
        5.70100e+00, 9.50000e+01, 3.78720e+00, 3.00000e+00, 3.07000e+02,
        2.10000e+01, 3.58770e+02, 1.83500e+01],
       [6.58800e-02, 0.00000e+00, 2.46000e+00, 0.00000e+00, 4.88000e-01,
        7.76500e+00, 8.33000e+01, 2.74100e+00, 2.00000e+00, 1.93000e+02,
        1.78000e+01, 3.95560e+02, 7.56000e+00],
       [2.49800e-02, 0.00000e+

In [15]:
lin_reg2.fit_gd(X_train, y_train,eta = 0.000001)

LinearRegression()

In [16]:
lin_reg2.score(X_test, y_test)

0.27806795012814023

In [17]:
lin_reg2.fit_gd(X_train, y_train,eta = 0.000001, n_iters=1e6)

LinearRegression()

In [18]:
lin_reg2.score(X_test, y_test)

0.7362073475538333